# Generated by Django 5.2.13 on 2026-04-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(choices=[('product_view', 'Product View'), ('product_click', 'Product Click'), ('add_to_cart', 'Add to Cart'), ('purchase', 'Purchase'), ('search', 'Search')], db_index=True, max_length=20)),
                ('product_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('device', models.CharField(blank=True, default='', max_length=20)),
                ('source_page', models.CharField(blank=True, default='', max_length=200)),
                ('keyword', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('event_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['user_id', 'timestamp'], name='tracking_ev_user_id_1cc566_idx'), models.Index(fields=['event_type', 'timestamp'], name='tracking_ev_event_t_674588_idx'), models.Index(fields=['product_id', 'event_type'], name='tracking_ev_product_8df775_idx')],
            },
        ),
    ]
